### ISSUE TITLE
Variable type mismatch for: g:ctrlp_custom_ignore

### ISSUE THREAD

**Issue by codeinabox** [voronkovich/ctrlp-symfony2.vim#1]
It seems that the plugin doesn't like me setting `g:ctrlp_custom_ignore` in my .vimrc as I get the following error

> Error detected while processing /Users/matt/dotfiles/.vim/bundle/ctrlp-symfony2.vim/plugin/ctrlp-symfony2.vim:
> line    1:
> E706: Variable type mismatch for: g:ctrlp_custom_ignore

**Comment by voronkovich** [comment]
Yes, you are right, plugin doesn't check if the variable was already defined. I will fix this later (or you can create a PR). Thanks!

**Comment by voronkovich** [comment]
Ok, I've fixed it.

**Comment by codeinabox** [comment]
Thank you for the quick fix :100:
