### ISSUE TITLE
Get Error "E464: Ambiguous use of user-defined command" after running ":CtrlPSymfony2"

### ISSUE THREAD

**Issue by chrisyue** [voronkovich/ctrlp-symfony2.vim#4]

**Comment by voronkovich** [comment]
@chrisyue, there is no command `CtrlPSymfony2`.

From the vim documentation:

```
Ambiguous use of user-defined command

There are two user-defined commands with a common name prefix, and you used
Command-line completion to execute one of them. |user-cmd-ambiguous|
Example:
    :command MyCommand1 echo "one"
    :command MyCommand2 echo "two"
    :MyCommand
```

You should use `:CtrlPSymfony2Entities`, `:CtrlPSymfony2Controllers` and etc. See readme https://github.com/voronkovich/ctrlp-symfony2.vim
I would recommend you to map those commands to keyboard keys, like this https://github.com/voronkovich/vimrc/blob/master/vimrc#L255

**Comment by chrisyue** [comment]
thanks for the reply, i'll try :)
