### ISSUE TITLE
Suggestion to use Travis CI to run specs

### ISSUE THREAD

**Issue by codeinabox** [voronkovich/ctrlp-symfony2.vim#7]
Using [vim-flavor it is possible run the Vim specs on Travis CI](http://whileimautomaton.net/2013/02/08211255)

**Comment by voronkovich** [comment]
@codeinabox, I agree with you. I will do it soon. Thanks for the link.

**Comment by voronkovich** [comment]
Done. Thanks for this proposal, @codeinabox!
