### ISSUE TITLE
CtrlPSymfony2Entities returns error 

### ISSUE THREAD

**Issue by codeinabox** [voronkovich/ctrlp-symfony2.vim#8]
I get the following error when running `CtrlPSymfony2Entities`. I can create a spec replicating the issue if you like.

> `find: -!: unknown primary or operator`

**Comment by voronkovich** [comment]
@codeinabox, please, write what a command shell and OS you use and an output of `find --help`.

**Comment by codeinabox** [comment]
OS X El Capitan 10.11.1 and zsh 5.1.1 (x86_64-apple-darwin13.4.0). It says `find --help` is an illegal option but if I just run `find` I get this

> usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
>       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

**Comment by voronkovich** [comment]
@codeinabox, it was just a typo in the `find` options, now it should work fine.

**Comment by codeinabox** [comment]
Great, this works fine for me now
